// 从 wlsdoblighting.com 原官网整理出的真实产品/新闻数据
// 参数（specs）字段原网站暂未填写详细数据，先留空，后续可在 Sanity 后台补充

export const products = [
  {
    name: 'Constant Current LED Flood Light DOB',
    category: 'outdoor',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAgqeXBywYosbb-wwIwoAY4oAY.jpg',
    shortDescription: 'High power outdoor flood light with constant current DOB driver integration, built for industrial and mining site lighting.',
    customizable: true,
    featured: true,
    order: 10,
  },
  {
    name: 'Linear DOB Flood Light',
    category: 'outdoor',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAgseabywYolPTuggEwoAY4oAY.jpg',
    shortDescription: 'Linear-format high power flood light in the DOB outdoor series, suited for wide-area industrial and mining applications.',
    customizable: true,
    featured: false,
    order: 20,
  },
  {
    name: 'LED Down Light DOB',
    category: 'commercial',
    imageUrl: 'https://33991007.s21i.faiusr.com/4/ABUIABAEGAAgxKCdywYolrDy9QMwkQY42AQ.png',
    shortDescription: 'Commercial-grade DOB down light for retail, hospitality and office ceiling installations.',
    customizable: true,
    featured: true,
    order: 30,
  },
  {
    name: 'A Bulb DOB',
    category: 'smart',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAglKedywYo2Pur6gcwoAY4oAY.jpg',
    shortDescription: "Smart-control-ready A-shape LED bulb built on WLS Lighting's DOB platform.",
    customizable: true,
    featured: true,
    order: 40,
  },
  {
    name: 'T Bulb Die-Cast Aluminum EMC Solution',
    category: 'furniture',
    imageUrl: 'https://33991007.s21i.faiusr.com/4/ABUIABAEGAAg5cadywYouNi_kQcwxAg4jAk.png',
    shortDescription: 'Die-cast aluminum T-bulb with EMC-compliant DOB architecture, designed for furniture and decorative fixtures.',
    customizable: true,
    featured: false,
    order: 50,
  },
  {
    name: 'Emergency AC/DC DOB Module',
    category: 'emergency',
    imageUrl: 'https://33991007.s21i.faiusr.com/4/ABUIABAEGAAg-qfcywYo2bTbmgUwvgE46wE.png',
    shortDescription: 'Dual AC/DC emergency lighting DOB module, engineered for backup and evacuation lighting reliability.',
    customizable: true,
    featured: true,
    order: 60,
  },
  {
    name: 'Panel Light DOB Driver',
    category: 'dob-driver',
    imageUrl: 'https://33991007.s21i.faiusr.com/4/ABUIABAEGAAgid_bywYo9r-n8wIwtgU46wM.png',
    shortDescription: "Dedicated DOB driver module for panel light applications, part of WLS Lighting's driver series.",
    customizable: true,
    featured: false,
    order: 70,
  },
];

export const news = [
  {
    title: 'Tanzanian Client Visits WLS Lighting for Business Exchange',
    category: 'company',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAgofudywYovunEigIwlRY4rR4.jpg',
    publishedAt: '2026-01-14T19:25:00+08:00',
    summary: 'Mr. Dashing from Tanzania visited WLS Lighting\'s Zhongshan headquarters to tour the showroom and production facilities and discuss collaboration for the African market.',
    body: [
      'On Jan.12, 2026, WLS Lighting warmly welcomed Mr. Dashing, a valued client from Tanzania, to its headquarters in Zhongshan, China.',
      "During the visit, Mr. Dashing toured the company's showroom and production facilities, gaining in-depth insights into WLS Lighting's latest LED products and innovative lighting solutions. The two sides held productive discussions on future collaboration, market trends, and customized lighting needs for the Tanzanian and African markets.",
      "WLS Lighting expressed sincere appreciation for Mr. Dashing's visit and ongoing partnership. The company reaffirmed its commitment to providing high-quality, energy-efficient lighting products and reliable service to clients worldwide.",
      'This visit further strengthens the business relationship between WLS Lighting and its partners in Tanzania, paving the way for continued growth and shared success in the lighting industry.',
    ],
  },
  {
    title: 'WLS Lighting Strengthens Foothold in Iran with Trusted DOB Expertise',
    category: 'company',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAgobmnywYo_biL-wYwtx040Bc.jpg',
    publishedAt: '2026-01-13T14:57:00+08:00',
    summary: 'WLS Lighting joined a leading lighting exhibition in Iran, showcasing DOB solutions and building distributor relationships in a high-potential market.',
    body: [
      'In November 2025, WLS Lighting participated with great enthusiasm in a leading lighting exhibition in Iran—an event that not only showcased technology but also built lasting connections.',
      'Beyond displaying our innovative Driver-on-Board (DOB) solutions, we engaged deeply with distributors, engineers, and industry partners, fostering friendships rooted in mutual trust and a shared vision for the future of lighting in Iran.',
      "Iran represents a market with immense potential, driven by urban development, energy-saving initiatives, and a growing demand for reliable, cost-effective lighting. Here, WLS Lighting's decade-long specialization in DOB technology offers distinct advantages. Our integrated DOB solutions eliminate external drivers, reduce system costs, enhance durability, and simplify installation—all critical factors for large-scale and diverse applications across residential, commercial, and industrial sectors.",
      'During the exhibition, the response was resounding. Clients appreciated not only the performance and adaptability of our DOB-based products but also the technical support and collaborative approach we bring. From robust T-Bulbs to sleek panel lights, our portfolio demonstrates how DOB can meet both functional needs and aesthetic preferences.',
      "As we left Iran, we carried with us more than business cards—we carried confidence. Confidence in the relationships we built, and in the role our DOB technology can play in illuminating Iran's path toward energy efficiency and sustainable development. WLS Lighting is committed to being a long-term partner in this journey, providing not just products, but reliable, innovative, and value-driven lighting solutions.",
    ],
  },
  {
    title: "WLS Lighting Explores Growth Opportunities in Vietnam's Dynamic Market",
    category: 'company',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAghrinywYogNfZyQUwgBQ4yg0.jpg',
    publishedAt: '2026-01-13T16:10:00+08:00',
    summary: 'WLS Lighting participated in a key Vietnam industry exhibition, conducting field visits to understand local installation practices and demand.',
    body: [
      'In Nov. 2025, WLS Lighting expanded its global engagement by participating in a key industry exhibition in Vietnam—a strategic move that allowed us to connect directly with local partners and gain firsthand insight into this rapidly growing market.',
      'Beyond showcasing our advanced Driver-on-Board (DOB) lighting solutions, our team took the opportunity to conduct field visits, observe local installation practices, and understand the specific needs and preferences of Vietnamese consumers and businesses.',
      "Vietnam represents a market full of vitality and potential, characterized by ongoing urbanization, infrastructure development, and a strong shift toward energy-efficient technologies. Through conversations with distributors, contractors, and lighting designers, we recognized a clear demand for reliable, cost-effective, and easy-to-install lighting products—precisely the strengths of WLS Lighting's DOB-integrated solutions.",
      "Our DOB technology, refined over more than a decade, offers distinct advantages for the Vietnamese market: simplified design, reduced maintenance, enhanced durability, and competitive pricing. These attributes align closely with the local emphasis on value, longevity, and adaptability across various applications.",
      "This visit has laid a solid foundation for our future strategy in Vietnam. By combining our technical expertise with on-the-ground insights, WLS Lighting is well-positioned to develop tailored solutions that meet local demands while maintaining our commitment to innovation and quality.",
    ],
  },
  {
    title: "Market Potential for WLS Lighting's 6W Panel Light in Egypt",
    category: 'case-study',
    imageUrl: 'https://33991007.s21i.faiusr.com/4/ABUIABAEGAAg4PeXywYo5t6QtwIwqgQ40QM.png',
    publishedAt: '2026-01-13T16:02:00+08:00',
    summary: "WLS Lighting's 6W integrated DOB panel light is well-positioned for Egypt's cost-conscious, energy-efficiency-focused lighting market.",
    body: [
      "WLS Lighting's 6W integrated panel light, featuring a sleek glass panel and acrylic construction, is strategically positioned for strong adoption in the Egyptian market. This product directly benefits from our core expertise as a dedicated DOB (Driver-on-Board) solutions provider.",
      'The Egyptian market prioritizes cost-effectiveness, durability, and energy efficiency due to rising electricity costs and a focus on sustainable development. Our DOB technology inherently meets these demands. By eliminating the external driver, this 6W panel light achieves a lower overall system cost, making it an accessible, high-quality option for both residential and commercial segments.',
      'The compact, all-in-one design enhances reliability—a critical factor in areas with voltage fluctuations—as it reduces failure points and improves thermal management within the unit. Furthermore, the elegant glass panel design caters to the growing consumer appetite for modern, aesthetically pleasing lighting.',
      "Our decade-long specialization in DOB ensures that this product is not just another light, but an optimized system, backed by the confidence of a 1-year warranty. For distributors and contractors in Egypt, this represents a reliable, value-driven product with a streamlined supply chain.",
    ],
  },
  {
    title: 'WLS Lighting: Powering the Future with Over a Decade of DOB Expertise',
    category: 'industry',
    imageUrl: 'https://33991007.s21i.faiusr.com/2/ABUIABACGAAg0pO9ywYohqrGmQEwqhU4-ws.jpg',
    publishedAt: '2026-01-13T16:00:00+08:00',
    summary: 'A decade of DOB specialization gives WLS Lighting a distinct edge in thermal management, circuit optimization and integrated system design.',
    body: [
      "The lighting industry's shift toward Driver-on-Board (DOB) technology represents more than just a trend—it's a fundamental redesign for efficiency, cost-effectiveness, and innovation. By integrating the driver directly onto the LED board, DOB eliminates bulky external components, slashing costs and unlocking sleek, versatile luminaire designs.",
      'At the forefront of this revolution is WLS Lighting, a company with a distinct advantage: over ten years of dedicated focus on perfecting DOB solutions. This deep-seated specialization translates into tangible benefits for our partners and the industry.',
      "Our long-term commitment means we've navigated DOB's evolution from its early stages. We've mastered the critical challenges of thermal management, electromagnetic compatibility, and circuit optimization that are crucial for reliability and longevity.",
      'This decade of expertise allows us to offer more than just components; we provide integrated, optimized systems. We collaborate closely with luminaire manufacturers to create tailored DOB modules that fit precise optical, mechanical, and electrical requirements.',
      'For the industry, WLS Lighting stands as a catalyst, empowering manufacturers to harness the full potential of DOB—driving the adoption of smarter, more sustainable, and architecturally flexible lighting solutions.',
    ],
  },
];
